eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        #loggerLevel: FULL


server:
  port: 0
spring:
  application:
    name: nation-cloud-auth-service
  datasource:
    platform:  org.hibernate.dialect.MariaDB103Dialect
    driver-class-name: org.mariadb.jdbc.Driver


nation:
  db:
    query:
      authority-query: "select NAME, ROLE from nation.user where NAME=?"
      authorize-query: "select NAME, PASSWORD, 1 as enabled  from nation.user where NAME=?"



---
spring:
  profiles: production
logging:
  level:
    ch:
      nation:
        core: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: ERROR
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        #loggerLevel: FULL
---
spring:
  profiles: debug
logging:
  level:
    ch:
      nation: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      security: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: FULL
