spring:
  application:
    name: nation-cloud-games-service
server:
  port: 0
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
  instance:
    preferIpAddress: true
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000




---
spring:
  profiles: production
logging:
  level:
    ch:
      nation:
        core: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: ERROR
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        #loggerLevel: FULL
---
spring:
  profiles: debug
logging:
  level:
    ch:
      nation:
        core: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: FULL
