version: '3.7'
services:
  eureka-service:
    container_name: eureka-service
    build:
       context: eurekaserver
       dockerfile: Dockerfile
    image:  nation-euraka-service:latest
    ports:
     - "8761:8761"
    networks:
     - spring-cloud-network
    environment:
      SERVER_PORT: 8761
    logging:
      driver: json-file


  zuul-service:
    container_name: zuul-service
    build:
      context: zuul
      dockerfile: Dockerfile
    image:  zuul:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    logging:
      driver: json-file
    depends_on:
      - eureka-service
      - db-service
      - user-runtime-service
      - user-service
      - units-service
      - prejudices-service
      - characteristics-service
      - skill-service
      - clazz-service
      - game-logic-service


  db:
    container_name: nation-db
    image: mariadb:10.4.8-bionic
    build:
      context: mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: nation
      MYSQL_DATABASE: nation
      MYSQL_USER: nation
      MYSQL_PASSWORD: nation
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network

  db-service:
    container_name: nation-cloud-database-service
    build:
      context: db-service
      dockerfile: Dockerfile
    image:  nation-cloud-database-service:latest
    ports:
      - "8889:8889"
      - "9999:9999"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9999
      MAIN_CLASS_NAME: ch.nation.dbservice.DBServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8889
      SPRING_DATASOURCE_URL: jdbc:mariadb://nation-db:3306/nation?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: nation
      SPRING_DATASOURCE_PASSWORD: nation
      SPRING_PROFILES_ACTIVE: mariadb-test
      #SPRING_PROFILES_ACTIVE: mariadb-install
    logging:
      driver: json-file
    depends_on:
      - eureka-service

# SERVICES
  game-service:
    container_name: nation-cloud-games-service
    build:
      context: game-service
      dockerfile: Dockerfile
    image:  nation-cloud-games-service:latest
    ports:
      - "8888:8888"
      - "9888:9888"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9888
      MAIN_CLASS_NAME: ch.nation.gameservice.GameServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8888
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service


  characteristics-service:
    container_name: nation-cloud-characteristics-service
    build:
      context: characteristics-service
      dockerfile: Dockerfile
    image:  nation-cloud-characteristics-service:latest
    ports:
      - "8879:8879"
      - "9879:9879"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9879
      MAIN_CLASS_NAME: ch.nation.characteristicsservice.CharacteristicsServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8879
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service


  clazz-service:
    container_name: nation-cloud-classes-service
    build:
      context: clazz-service
      dockerfile: Dockerfile
    image:  nation-cloud-classes-service:latest
    ports:
      - "8880:8880"
      - "9880:9880"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9880
      MAIN_CLASS_NAME: ch.nation.clazzservice.ClazzServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8880
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service

  game-logic-service:
    container_name: nation-cloud-game-logics-service
    build:
      context: game-logic-service
      dockerfile: Dockerfile
    image:  nation-cloud-game-logics-service:latest
    ports:
      - "8881:8881"
      - "9881:9881"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9881
      MAIN_CLASS_NAME: ch.nation.gamelogicservice.GamelogicserviceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8881
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service

  moves-service:
    container_name: nation-cloud-moves-service
    build:
      context: moves-service
      dockerfile: Dockerfile
    image:  nation-cloud-moves-service:latest
    ports:
      - "8882:8882"
      - "9882:9882"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9882
      MAIN_CLASS_NAME: ch.nation.movesservice.MovesServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8882
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service

  prejudices-service:
    container_name: nation-cloud-prejudices-service
    build:
      context: prejudice-service
      dockerfile: Dockerfile
    image:  nation-cloud-prejudices-service:latest
    ports:
      - "8883:8883"
      - "9883:9883"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9883
      MAIN_CLASS_NAME: ch.nation.prejudiceservice.PrejudiceServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8883
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service


  skill-service:
    container_name: nation-cloud-skills-service
    build:
      context: skill-service
      dockerfile: Dockerfile
    image:  nation-cloud-skills-service:latest
    ports:
      - "8884:8884"
      - "9884:9884"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9884
      MAIN_CLASS_NAME: ch.nation.skillservice.SkillServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8884
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service


  user-runtime-service:
    container_name: nation-cloud-user-runtimes-service
    build:
      context: user-runtime-service
      dockerfile: Dockerfile
    image:  nation-cloud-user-runtimes-service:latest
    ports:
      - "8885:8885"
      - "9885:9885"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9885
      MAIN_CLASS_NAME: ch.nation.userruntimeservice.UserRuntimeServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8885
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service

  units-service:
    container_name: nation-cloud-units-service
    build:
      context: units-service
      dockerfile: Dockerfile
    image:  nation-cloud-units-service:latest
    ports:
      - "8875:8875"
      - "9875:9875"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9875
      MAIN_CLASS_NAME: ch.nation.unitsservice.UnitsServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8875
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service

  user-service:
    container_name: nation-cloud-users-service
    build:
      context: user-service
      dockerfile: Dockerfile
    image:  nation-cloud-users-service:latest
    ports:
      - "8886:8886"
      - "9886:9886"
    networks:
      - spring-cloud-network
    environment:
      DEBUG_PORT: 9886
      MAIN_CLASS_NAME: ch.nation.userservice.UserServiceApplication
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8886
      SPRING_PROFILES_ACTIVE: production
    logging:
      driver: json-file
    depends_on:
      - eureka-service

  nginx:
    container_name: nation-cloud-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    image:  nation-cloud-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../downloads:/usr/share/nginx/html/downloads
    networks:
      - spring-cloud-network
    logging:
      driver: json-file
    depends_on:
      - zuul-service


#NETWORK
networks:
  spring-cloud-network:
    driver: bridge
