version: '3.7'
services:
  eureka-service:
    container_name: eureka-service
    build:
       context: eurekaserver
       dockerfile: Dockerfile
    image:  nation-euraka-service:latest
    ports:
     - "8761:8761"
    networks:
     - spring-cloud-network
    environment:
      SERVER_PORT: 8761
    logging:
      driver: json-file
  zuul-service:
    container_name: zuul-proxy-service
    build:
      context: zuul
      dockerfile: Dockerfile
    image:  zuul:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    logging:
      driver: json-file
    depends_on:
      - eureka-service
  game-service:
    container_name: nation-cloud-games-service
    build:
      context: game-service
      dockerfile: Dockerfile
    image:  nation-cloud-games-service:latest
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8888
    logging:
      driver: json-file
    depends_on:
      - eureka-service
      - zuul-service
  db:
    container_name: nation-db
    image: mariadb:10.4.8-bionic
    environment:
      MYSQL_ROOT_PASSWORD: nation
      MYSQL_DATABASE: nation
      MYSQL_USER: nation
      MYSQL_PASSWORD: nation
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network

  db-service:
    container_name: nation-cloud-database-service
    build:
      context: db-service
      dockerfile: Dockerfile
    image:  nation-cloud-database-service:latest
    ports:
      - "8889:8889"
    networks:
      - spring-cloud-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SERVER_PORT: 8889
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/nation?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: nation
      SPRING_DATASOURCE_PASSWORD: nation
      SPRING_PROFILES_ACTIVE: mariadb-test
    logging:
      driver: json-file
    depends_on:
      - eureka-service
      - db
      - zuul-service

networks:
  spring-cloud-network:
    driver: bridge
