spring:
  application:
    name: nation-database-service
  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      #defaultMediaType: application/json+hal

server:
  #port: 0
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

