eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
    registerWithEureka: true
  instance:
    preferIpAddress: true
logging:
  level:
    ch:
      nation:
        rest:
          clients: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 201998

ribbon:
  ReadTimeout: 201998
  connection-timeout: 201998


security:
  oauth2:
    resource:
      jwt:
        key-value: 123


zuul:
  prefix: /api/rest/v1
  sensitiveHeaders:
  routes:
    game-auth-service-path:
      path: /oauth/**
      url: http://nation-cloud-auth-service:9000/oauth
    game-logic-service-path:
      path: /logic/**
      serviceId: nation-cloud-auth-service
    game-resource-characteristics-service-path:
      path: /characteristics/**
      serviceId: nation-cloud-characteristics-service
    game-resource-user-runtimes-service-path:
      path: /user-runtimes/**
      serviceId: nation-cloud-user-runtimes-service
    game-resource-users-service-path:
      path: /users/**
      serviceId: nation-cloud-users-service
    game-resource-moves-service-path:
      path: /moves/**
      serviceId: nation-cloud-moves-service
    game-resource-prejudices-service-path:
      path: /prejudices/**
      serviceId: nation-cloud-prejudices-service
    game-resource-skills-service-path:
      path: /skills/**
      serviceId: nation-cloud-skills-service
    game-resource-units-service-path:
      path: /units/**
      serviceId: nation-cloud-units-service
    game-resource-game-service-path:
      path: /games/**
      serviceId: nation-cloud-games-service
    game-resource-classes-service-path:
      path: /classes/**
      serviceId: nation-cloud-classes-service


server:
  port: 8080
spring:
  application:
    name: nation-cloud-zuul-service
