eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka}"
    registerWithEureka: true
  instance:
    preferIpAddress: true
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: FULL
logging:
  level:
    ch:
      nation:
        rest:
          clients: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG



zuul:
  prefix: /api/rest/v1
  routes:
    game-logic-service-path:
      path: /logic/**
      serviceId: nation-cloud-game-logic-service
    game-resource-characteristics-service-path:
      path: /characteristics/**
      serviceId: nation-cloud-characteristics-service
    game-resource-user-runtimes-service-path:
      path: /user-runtimes/**
      serviceId: nation-cloud-user-runtime-service
    game-resource-users-service-path:
      path: /users/**
      serviceId: nation-cloud-user-service
    game-resource-moves-service-path:
      path: /moves/**
      serviceId: nation-cloud-moves-service
    game-resource-prejudices-service-path:
      path: /prejudices/**
      serviceId: nation-cloud-prejudice-service
    game-resource-skills-service-path:
      path: /skills/**
      serviceId: nation-cloud-skills-service
    game-resource-units-service-path:
      path: /units/**
      serviceId: nation-cloud-units-service
    game-resource-game-service-path:
      path: /games/**
      serviceId: nation-cloud-game-service
    game-resource-classes-service-path:
      path: /classes/**
      serviceId: nation-cloud-clazz-service


server:
  port: 8080
spring:
  application:
    name: nation-cloud-zuul-service
