spring:
  application:
    name: nation-cloud-game-logic-service
server:
  #port: 0
  port: 8082
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


#DEBUG Settings
logging:
  level:
    ch:
      nation:
        rest:
          clients: DEBUG

