server:
  #port: 0
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  profiles:
    active: local
  application:
    name: nation-database-service

nation:
  units:
    include-dummy: "${INCLUDE_DUMMY_PLAYER:false}"

---
spring:
  profiles: local
  flyway:
    baselineOnMigrate: true
  h2:
    console:
      enabled: true
    path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    #     ddl-auto: create-drop
    show-sql: true
    jdbc:
      time_zone: UTC+2
  data:
    rest:
    #defaultMediaType: application/json+hal
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
      org.springframework.orm.jpa: INFO
      org.springframework.transaction: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
---
spring:
  profiles: debug

  data:
    rest:
    #defaultMediaType: application/json+hal
  logging:
    level:
      org:
        springframework:
          web: ERROR
          cache: TRACE
          orm:
            jpa: ERROR
        hibernate: ERROR
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

        show_sql: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false

    generate-ddl: true
  datasource:
    platform:  org.hibernate.dialect.MariaDB103Dialect
    driver-class-name: org.mariadb.jdbc.Driver
---

spring:
  profiles: mariadb-install
  application:
    name: nation-database-service

  data:
    rest:
    #defaultMediaType: application/json+hal
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
      org.springframework.orm.jpa: INFO
      org.springframework.transaction: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:

        show_sql: true
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false

    generate-ddl: true
  datasource:
    platform:  org.hibernate.dialect.MariaDB103Dialect
    driver-class-name: org.mariadb.jdbc.Driver
---
